"""Shared package with cross-module schemas."""

from shared.schemas import (
    Action,
    ArtifactRef,
    ChatMessage,
    ChordAnnotation,
    ChordDistribution,
    ChordExplanation,
    ChordSuggestion,
    ChordProgression,
    ChordSymbolDerivation,
    EmotionVector,
    ExplanationReport,
    ExplanationPart,
    GenerationRequest,
    GenerationResponse,
    LyricSuggestion,
    MelodyNote,
    MelodyProfile,
    MelodySuggestion,
    NoteEvent,
    Progression,
    RefinementPlan,
    SessionState,
    SessionSummary,
)

__all__ = [
    "Action",
    "ArtifactRef",
    "ChatMessage",
    "ChordAnnotation",
    "ChordDistribution",
    "ChordExplanation",
    "ChordSymbolDerivation",
    "MelodyNote",
    "NoteEvent",
    "MelodyProfile",
    "EmotionVector",
    "MelodySuggestion",
    "LyricSuggestion",
    "ChordProgression",
    "Progression",
    "ChordSuggestion",
    "RefinementPlan",
    "ExplanationReport",
    "ExplanationPart",
    "GenerationRequest",
    "GenerationResponse",
    "SessionState",
    "SessionSummary",
]
